[package]
name = "xdr-rs-serialize"
version = "0.1.0"
authors = ["Kyle Bartush <kbartush@kochava.com>"]
edition = "2018"

[dependencies]
xdr-rs-serialize-derive = { path = "xdr-rs-serialize-derive" }
